### ISSUE TITLE
Fix title on docs

### ISSUE THREAD

**Issue by Bgeninatti** [Bgeninatti/pythonium#27]
[Docs main page](https://pythonium.readthedocs.io/en/latest/index.html) show _\<no title\>_ on tab title

**Comment by danger-ahead** [comment]
Hi, I am interested in fixing the issue. Can you provide a more detailed info on the task?
Thanks. 
Kindly consider assigning me :)

**Comment by Bgeninatti** [comment]
Hi @danger-ahead! 

Glad that you are interested in  Pythonium.

I checked again on this and noticed that this issue was resolved as a side effect of some [documentation improvements](https://github.com/Bgeninatti/pythonium/pull/28) applied yesterday.

I'll be working on the tutorial for Pythonium during the next days, and I will appreciate any feedback on that :smiley: 

If you are interested, you can follow up on #5, and the first chapter is already available :wink: -> [here](https://pythonium.readthedocs.io/en/latest/tutorial.html)!

cheers!
